name: Idea or Feature
description: Propose a new feature to improve the package.
labels: ["enhancement"]

body:
  - type: textarea
    attributes:
      label: What new feature would you like to see?
      description: A clear and concise description of what you would like added and why.
    validations:
      required: true
