name: release

on:
  push:
    branches:
      - develop
# on:
#   release:
#     types: [published]

jobs:
  build_sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: "3.10"
      - run: |
          python -m pip install build
          pip install -e .
      - name: Build sdist
        run: python -m build --sdist

  build_wheels:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["39", "310"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.1
        env:
          CIBW_BUILD: cp${{ matrix.python-version }}-*
      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  release:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          verbose: true
