name: tests
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: setup.py

      - name: Install pip packages
        run: |
          pip install -r tests/requirements.txt
          pip install .

      - name: Set up Covalent server
        run: |
          echo "y"
          covalent start

      - name: Run tests with pytest
        run: pytest --cov=covalent_hpc_plugin --cov-report=xml

      - name: Stop Covalent server
        run: covalent stop

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
